// Mocks generated by Mockito 5.0.17 from annotations
// in flutter_demo_app/test/breath_list/datasources/data/breath_local_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_demo_app/database/db_helper_dynamic.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i2.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Database?> get database => (super.noSuchMethod(
      Invocation.getter(#database),
      returnValue: Future<_i4.Database?>.value()) as _i3.Future<_i4.Database?>);
  @override
  _i3.Future<int> insert(dynamic table, Map<String, dynamic>? row) =>
      (super.noSuchMethod(Invocation.method(#insert, [table, row]),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  _i3.Future<List<Map<String, dynamic>>> queryAllRows(dynamic table) =>
      (super.noSuchMethod(Invocation.method(#queryAllRows, [table]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i3.Future<List<Map<String, dynamic>>>);
  @override
  _i3.Future<int?> queryRowCount(dynamic table) =>
      (super.noSuchMethod(Invocation.method(#queryRowCount, [table]),
          returnValue: Future<int?>.value()) as _i3.Future<int?>);
  @override
  _i3.Future<int> update(
          dynamic columnId, dynamic table, Map<String, dynamic>? row) =>
      (super.noSuchMethod(Invocation.method(#update, [columnId, table, row]),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  _i3.Future<int> delete(int? id, dynamic table, dynamic columnId) =>
      (super.noSuchMethod(Invocation.method(#delete, [id, table, columnId]),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDBHelperForTest extends _i1.Mock implements _i2.DatabaseHelper {
  @override
  _i3.Future<_i4.Database?> get database => (super.noSuchMethod(
      Invocation.getter(#database),
      returnValue: Future<_i4.Database?>.value()) as _i3.Future<_i4.Database?>);
  @override
  _i3.Future<int> insert(dynamic table, Map<String, dynamic>? row) =>
      (super.noSuchMethod(Invocation.method(#insert, [table, row]),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  _i3.Future<List<Map<String, dynamic>>> queryAllRows(dynamic table) =>
      (super.noSuchMethod(Invocation.method(#queryAllRows, [table]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i3.Future<List<Map<String, dynamic>>>);
  @override
  _i3.Future<int?> queryRowCount(dynamic table) =>
      (super.noSuchMethod(Invocation.method(#queryRowCount, [table]),
          returnValue: Future<int?>.value()) as _i3.Future<int?>);
  @override
  _i3.Future<int> update(
          dynamic columnId, dynamic table, Map<String, dynamic>? row) =>
      (super.noSuchMethod(Invocation.method(#update, [columnId, table, row]),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  _i3.Future<int> delete(int? id, dynamic table, dynamic columnId) =>
      (super.noSuchMethod(Invocation.method(#delete, [id, table, columnId]),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
}
