// Mocks generated by Mockito 5.0.17 from annotations
// in flutter_demo_app/test/auth/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_demo_app/auth/data/datasources/auth_remote_data_source.dart'
    as _i5;
import 'package:flutter_demo_app/auth/models/auth.dart' as _i2;
import 'package:flutter_demo_app/auth/models/user_data.dart' as _i6;
import 'package:flutter_demo_app/core/network/network_info.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAuth_0 extends _i1.Fake implements _i2.Auth {}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i3.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i5.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Auth> loginUser(_i6.UserData? userData) =>
      (super.noSuchMethod(Invocation.method(#loginUser, [userData]),
              returnValue: Future<_i2.Auth>.value(_FakeAuth_0()))
          as _i4.Future<_i2.Auth>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNumberTriviaRemoteDataSourceForTest extends _i1.Mock
    implements _i5.AuthRemoteDataSource {
  @override
  _i4.Future<_i2.Auth> loginUser(_i6.UserData? userData) =>
      (super.noSuchMethod(Invocation.method(#loginUser, [userData]),
              returnValue: Future<_i2.Auth>.value(_FakeAuth_0()))
          as _i4.Future<_i2.Auth>);
}
